version = 1
disable_existing_loggers = true

[formatters.short]
format = '%(asctime)s - %(levelname)s - %(name)s - %(message)s'

[formatters.long]
format = '%(asctime)s - %(levelname)s - %(name)s - %(process)s - %(module)s - %(filename)s - %(funcName)s - %(lineno)d - %(message)s'

[handlers.console]
level = 'INFO'
formatter = 'long'
class = 'logging.StreamHandler'
stream = 'ext://sys.stdout'

[handlers.info_rfh]
level = 'INFO'
formatter = 'short'
class = 'logging.handlers.RotatingFileHandler'
filename = 'info.log'
mode = 'a'
maxBytes = 1048576
backupCount = 3

[handlers.critical_mail_handler]
level = 'CRITICAL'
formatter = 'long'
class = 'logging.handlers.SMTPHandler'
mailhost = 'localhost'
fromaddr = 'monitoring@domain.com'
toaddrs = ['dev@domain.com', 'qa@domain.com']
subject = 'Critical error with application name'

[loggers.""]
handlers = ['console', 'info_rfh' ]
level = 'WARNING'
propagate = true
